packages:
  - 'apps/*'
  - 'packages/*'
  - 'packages/infrastructure/*'

disallowWorkspaceCycles: true
failIfNoMatch: true

allowBuilds:
  '@ast-grep/cli': true
  '@sentry/cli@2.58.6': true
  lefthook: true
